DNS based setup needs domain name
frappe/frappe_docs pull request #11
Opened 2020-07-07 22:08 UTC by TurkerTunali

I think that it would be better if admin specifies the domain names via bench.

2020-08-11 09:02 UTC, rmehta commented on frappe_docs/www/docs/user/en/bench/guides/setup-multitenancy.md
> +* Set default site for bench cli
`bench use` is a really had system and leads to more problems as you add more sites. Let's skip that!

2020-08-28 13:08 UTC, barredterra requested changes

2020-08-28 13:08 UTC, barredterra commented on frappe_docs/www/docs/user/en/bench/guides/setup-multitenancy.md
> +	`bench setup add-domain site2name.com`
```suggestion
* Set domain name of the first site

	`bench setup add-domain --site site1name site1name.com`	

* Create a new site

	`bench new-site site2name`
	
* Set domain name of the second site

	`bench setup add-domain --site site2name site2name.com`	

```

2021-11-26 14:05 UTC, closed without merging

2021-11-26 14:05 UTC, TurkerTunali commented
It seems best to close it.