docs(WIP): Utils Init
frappe/frappe_docs pull request #134
Opened 2021-05-05 14:17 UTC by NagariaHussain

Add docs for must-know utility functions available in Frappe Framework.

2021-05-25 08:13 UTC, netchampfaris reviewed
Thanks for writing this!

Minor nitpick: we should be consistent in how we document things. For example, the [database API documentation](https://frappeframework.com/docs/user/en/api/database) doesn't use words like "Function signature" and "Example Usage". Either we should add these to that page, or we should remove it from this page.

2021-05-25 08:16 UTC, NagariaHussain commented
> Thanks for writing this!
> 
> 
> 
> Minor nitpick: we should be consistent in how we document things. For example, the [database API documentation](https://frappeframework.com/docs/user/en/api/database) doesn't use words like "Function signature" and "Example Usage". Either we should add these to that page, or we should remove it from this page.


Let me add it to the database API page as well. Not many functions there.

2021-06-08 11:39 UTC, gavindsouza requested changes

2021-06-08 11:39 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/api/utils.md
> +
Single space will have the same effect. This just makes it inconvenient to understand the visual blocks while reading the raw file. Consider getting rid of the extra empty lines before all codeblocks.

2021-06-08 11:39 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/api/utils.md
> +```
Probably best to promote usage of just one of those to avoid confusion. I prefer to use the `today` API since it looks cleaner

2021-06-08 11:39 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/api/utils.md
> +Returns the current datetime in the format 'yyyy-mm-dd hh:mm:ss'
```suggestion
Returns the current datetime in the format **yyyy-mm-dd hh:mm:ss**
```

I think ** provides better emphasis than '

2021-06-08 11:39 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/api/utils.md
> +`def sendmail(recipients=[], sender="", subject="No Subject", message="No Message", as_markdown=False, template=None, args=None, **kwargs)`
```suggestion
`sendmail(recipients=[], sender="", subject="No Subject", message="No Message", as_markdown=False, template=None, args=None, **kwargs)`
```

Only for the sake of consistency. 😆

2021-06-08 11:39 UTC, gavindsouza commented on frappe_docs/www/docs/_sidebar.json
> +			{ "title": "Common Utilities", "route": "/docs/user/en/api/utils" },
Link this and the other missing titles in https://frappeframework.com/docs/user/en/api#python too?

2021-06-14 11:29 UTC, NagariaHussain commented on frappe_docs/www/docs/_sidebar.json
> +			{ "title": "Common Utilities", "route": "/docs/user/en/api/utils" },
Done.

2021-06-14 14:44 UTC, ankush commented
anything holding the merge? 🤔  @gavindsouza @netchampfaris

2021-06-14 14:53 UTC, netchampfaris approved these changes

2021-06-14 14:55 UTC, merged