docs(WIP): Docs redisearch
frappe/frappe_docs pull request #145
Opened 2021-05-28 01:35 UTC by NagariaHussain

Updated documentation for Redis 6 and Redisearch module.

2021-06-08 09:08 UTC, gavindsouza requested changes

2021-06-08 09:08 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/installation.md
> +  Redis 6                                       (caching and realtime updates)
System requirements vary depending on Frappe versions. That should be made evident here. Specify that Version 13 requires Redis 6. But then we have develop which has higher Node requirements too....

This should be tracked on it's own separate page. 

Is there a corresponding Frappe PR for this? Or do the older client versions simply work?

2021-06-08 10:04 UTC, NagariaHussain commented on frappe_docs/www/docs/user/en/installation.md
> +  Redis 6                                       (caching and realtime updates)
Works without any changes on v13.

2021-06-23 14:00 UTC, NagariaHussain commented on frappe_docs/www/docs/user/en/installation.md
> +## [ERPNext] Optional: Redisearch Redis Module
I will move this to ERPNext docs. Need to figure out where.

2021-07-23 10:23 UTC, NagariaHussain commented
Moved via https://github.com/frappe/erpnext_documentation/pull/375

2021-07-23 10:24 UTC, closed without merging

2021-07-23 11:23 UTC, gavindsouza commented
Don't we need to upgrade Redis to v6 too? @NagariaHussain

2021-07-23 11:26 UTC, NagariaHussain commented
> Don't we need to upgrade Redis to v6 too? @NagariaHussain 

Yes, it is good we update the version here too. Will create other PR which updates the docs just for Redis 6. On MacOS, its default now.