Added bench execute
frappe/frappe_docs pull request #171
Opened 2021-07-30 09:56 UTC by TurkerTunali

For the https://github.com/frappe/frappe_docs/pull/87

2021-09-06 04:06 UTC, rmehta requested changes

2021-09-06 04:06 UTC, rmehta commented on frappe_docs/www/docs/user/en/bench/reference/execute.md
> + - `--args` Arguments for the method. Ex: --args "{'ITEM_A', 'WAREHOUSE_B'}"
seems like an incorrect dict format

2021-09-06 08:39 UTC, TurkerTunali commented on frappe_docs/www/docs/user/en/bench/reference/execute.md
> + - `--args` Arguments for the method. Ex: --args "{'ITEM_A', 'WAREHOUSE_B'}"
This is what I use:
bench --site site1.local execute erpnext.stock.stock_balance.repost_stock --args "{'TECNO-1', 'Mal Kabul - YT'}"

2021-12-06 07:05 UTC, hasnain2808 commented
Hi @TurkerTunali ,

We moved to a new simpler contribution pipeline. Please move this PR with the requested changes to the new site.

You can now directly contribute to [frappeframework.com](https://frappeframework.com/). For new contribution guidelines, refer to [frappeframework.com/contribute](https://frappeframework.com/contribute).

Thanks for the contribution!

2021-12-06 07:05 UTC, closed without merging