docs: docs for open_mapped_doc and get_mapped_doc
frappe/frappe_docs pull request #49
Opened 2020-09-29 11:06 UTC by hasnain2808

docs for open_mapped_doc and get_mapped_doc. These functions are used at multiple places in erpnext to sync data between documents

2020-09-30 06:43 UTC, scmmishra requested changes
Can you add a screenshot in the description?

2020-09-30 06:43 UTC, scmmishra commented on frappe_docs/www/docs/user/en/api/js-utils.md
> +create_dunning: function(frm) {
Can you use a frappe specific example?

2020-09-30 15:02 UTC, hasnain2808 commented on frappe_docs/www/docs/user/en/api/js-utils.md
> +create_dunning: function(frm) {
Done

2020-10-16 07:04 UTC, scmmishra requested changes

2020-10-16 07:04 UTC, scmmishra commented on frappe_docs/www/docs/user/en/api/js-utils.md
> +create_movie_review: function(frm) {
Continue on the library management application example

2020-10-16 07:04 UTC, scmmishra commented on frappe_docs/www/docs/user/en/api/js-utils.md
> +## frappe.model.open\_mapped\_doc
Also explain what mapped_doc does

2020-10-16 07:04 UTC, scmmishra commented on frappe_docs/www/docs/user/en/api/js-utils.md
> +Extract docs, docinfo (attachments, comments, assignments) from incoming request and set in `locals` and `frappe.model.docinfo`
Needs more explanantion

2021-03-23 07:35 UTC, closed without merging