docs(hooks): Overriding Form Scripts
frappe/frappe_docs pull request #55
Opened 2020-10-14 15:35 UTC by abhishekbalam

Added docs for overriding Form Scripts

![image](https://user-images.githubusercontent.com/15175501/96011692-de0d6080-0e60-11eb-998c-53a8c7c2d77f.png)

2020-10-14 17:08 UTC, netchampfaris requested changes

2020-10-14 17:08 UTC, netchampfaris commented on frappe_docs/www/docs/user/en/python-api/hooks.md
> +> will override those in the respective standard form script.
Can we make this more clear?

2020-10-14 17:08 UTC, netchampfaris commented on frappe_docs/www/docs/user/en/python-api/hooks.md
> +### Override Form Scripts
Also, this needs to be added to the table at the bottom of the page

2020-10-15 07:05 UTC, abhishekbalam commented on frappe_docs/www/docs/user/en/python-api/hooks.md
> +### Override Form Scripts
Done

2020-10-15 07:09 UTC, abhishekbalam commented on frappe_docs/www/docs/user/en/python-api/hooks.md
> +> will override those in the respective standard form script.
Is this better?

![image](https://user-images.githubusercontent.com/15175501/96088695-72200c00-0ee3-11eb-8161-90d6ddba7848.png)

2020-10-16 09:41 UTC, netchampfaris approved these changes

2020-10-16 09:42 UTC, merged