FIX : bench config set-common-config documentation
frappe/frappe_docs pull request #69
Opened 2020-11-24 08:43 UTC by FHenry

bench config set-common-config or remove-comon-config need 'configs', '-c', '--config' to send config value
line 53 of bench/commands/config.py

`@click.command('set-common-config', help='Set value in common config')
@click.option('configs', '-c', '--config', multiple=True, type=(str, str))
def set_common_config(configs):`

If this option is not provided, there is error 
for exemple 

```
$bench config set-common-config enable_frappe_logger true
Error: Got unexpected extra argument (enable_frappe_logger)
```
but 

`$bench config set-common-config -c enable_frappe_logger true`

is ok

2020-12-01 04:56 UTC, gavindsouza requested changes

2020-12-01 04:56 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/bench/bench-commands.md
> + - **remove-common-config**: Remove specific keys from current bench's common with parameters -c, configs or --config
Thanks for this PR!

There's no -c option for the `remove-common-config`.

![Screenshot 2020-12-01 at 10 23 15 AM](https://user-images.githubusercontent.com/36654812/100698753-3ec80c80-33bf-11eb-90c6-b368685317ad.png)

@FHenry

2020-12-01 04:56 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/bench/bench-commands.md
> +```
```suggestion
```

This may not be the correct file to add examples. Can you checkout the [Frappe Commands](https://frappeframework.com/docs/user/en/bench/frappe-commands) to see the general structure of our commands docs?

2020-12-01 04:56 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/bench/bench-commands.md
```suggestion
```

This line is unnecessary.

2020-12-01 08:18 UTC, FHenry commented on frappe_docs/www/docs/user/en/bench/bench-commands.md
Ok corrected

2020-12-02 08:22 UTC, gavindsouza approved these changes
Thanks for your contribution @FHenry 👍🏼

2020-12-02 08:23 UTC, merged

2020-12-02 08:29 UTC, FHenry commented
> Thanks for your contribution @FHenry 👍🏼 

It's just the beginning 😊