docs: file attachments
frappe/frappe_docs pull request #89
Opened 2021-02-03 07:20 UTC by walstanb

PR: [frappe/frappe#12160](https://github.com/frappe/frappe/pull/12160)

2021-02-08 09:54 UTC, netchampfaris requested changes

2021-02-08 09:54 UTC, netchampfaris commented on frappe_docs/www/docs/user/en/desk/attachments.md
> +# Attachment of Files
Page attributes missing
```
---
title: Attachments
description: ...
---
```

2021-02-08 12:19 UTC, gavindsouza commented
> Also proposing removal of old page in ERPNext docs.

@walstanb +1 for this. We can add a redirect in [ERPNext Documentation](https://github.com/frappe/erpnext_documentation/blob/master/erpnext_documentation/hooks.py) to this.

2021-02-09 07:39 UTC, sagarvora commented
PR for modifications in ERPNext Docs: https://github.com/frappe/erpnext_documentation/pull/247

2021-03-05 13:05 UTC, merged