docs: Update MariaDB installation instructions for Ubuntu
frappe/frappe_docs pull request #98
Opened 2021-02-24 17:53 UTC by NagariaHussain

Fixes #97 

The default Ubuntu 20.04 repository includes MariaDB 10.3 package (which is required by Frappe while) while Ubuntu 18.04's default repository has MariaDB 10.1. So, the external PPA should not be added in Ubuntu 20.04. 

If the external PPA repository is added to Ubuntu 20.04 system, it causes conflicting issues while MariaDB installation.

2021-03-16 07:54 UTC, gavindsouza requested changes

2021-03-16 07:54 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/installation.md
> +# Not to be ran for Ubuntu 20.04
```suggestion
# Not to be run for Ubuntu 20.04
```

2021-03-16 07:54 UTC, gavindsouza commented on frappe_docs/www/docs/user/en/installation.md
> +# Not to be ran for Ubuntu 20.04
Better to separate blocks with spaces instead of adding the same comment twice.

2021-03-22 09:32 UTC, NagariaHussain commented on frappe_docs/www/docs/user/en/installation.md
> +# Not to be ran for Ubuntu 20.04
Separated the commands into two blocks.

2021-03-22 10:51 UTC, gavindsouza approved these changes

2021-03-22 10:51 UTC, merged